const allRewards = [
  "date night",
  "naked sauna",
  "shower together",
  "back massage w/ lotion",
  "go down...",
  "bj",
  "date night",
  "you choose!",
  "sexy time",
  "shower together",
  "let's get it on",
  "lotion massage of choice",
  "foot massage",
  "use toys",
  "bj",
  "your pick!",
  "go down...",
  "sexy time!",
  "bj",
  "closet quickie",
  "69",
  "massage gun",
  "go down...",
  "massage gun",
  "massage of your choice",
  "bj",
  "naked sauna",
  "massage gun",
  "use toys",
  "69",
  "neck massage",
  "shower together",
  "closet quickie",
  "date night",
  "back massage w/ lotion",
];
